### ISSUE TITLE
窗口不会自动弹出

### ISSUE THREAD

**Issue by HairlessVillager** [banzhusoft/devcpp-cn#1]
在Dev-cpp已经打开时再打开一个.cpp文件不会自动弹出Dev-cpp窗口。这个bug（特性？）在Dev-cpp 5.11就有了

**Comment by banzhusoft** [comment]
现在的Windows 系统不允许应用程序自己跳到最前面。
你可以试试用WPS做类似的文件操作，就会发现是一样的。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："HairlessVillager "<notifications@github.com&gt;;
发送时间：2020年7月7日(星期二) 晚上9:22
收件人："banzhusoft/devcpp-cn" <devcpp-cn@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[banzhusoft/devcpp-cn] 窗口不会自动弹出 (#1)
-----------------------------------

 

 
在Dev-cpp已经打开时再打开一个.cpp文件不会自动弹出Dev-cpp窗口。这个bug（特性？）在Dev-cpp 5.11就有了
