### ISSUE TITLE
[问题] 同时打开 3 个或以上文件时失去响应

### ISSUE THREAD

**Issue by mrj1018** [banzhusoft/devcpp-cn#10]
这似乎是一个 Dev-C++ 本身的问题，因为老版本的 Dev-C++ 也有同样的问题。

出现问题的场景：先关闭 Dev-C++，再在资源管理器中同时选中三个或以上的 cpp 文件，用 Dev-C++ 打开，会卡在“解析文件”阶段，且程序失去响应。如果打开一个或两个文件则不会出现此问题。

系统：Windows 10 64 bit

进行测试时尚有 2 GB 以上可用内存。

**Comment by banzhusoft** [comment]
罕见的操作，需要开发者耗费大量时间也难以解决的问题。
不如一个一个地双击 cpp 文件，避开这个问题。

**Comment by mrj1018** [comment]
嗯，确实也没有很迫切的需求，只是看看能不能解决这个，所以如果很难解决就算了吧。
