### ISSUE TITLE
对窗口拉伸后的 UI 异常

### ISSUE THREAD

**Issue by HairlessVillager** [banzhusoft/devcpp-cn#13]
如图：

![dpdOjP.png](https://s1.ax1x.com/2020/08/13/dpdOjP.png)

![dpdjnf.png](https://s1.ax1x.com/2020/08/13/dpdjnf.png)

图片链接：https://imgchr.com/i/dpdOjP   https://imgchr.com/i/dpdjnf

当然这个 bug 可修可不修，毕竟我觉得不会有下个像我一样变态得把窗口捣鼓来捣鼓去的人。XD

**Comment by banzhusoft** [comment]
我自己试过多次，没有出现这种情况。
