### ISSUE TITLE
能添加蓝奏云的下载链接么？

### ISSUE THREAD

**Issue by TheBadZhang** [banzhusoft/devcpp-cn#14]
lanzou.com

**Comment by banzhusoft** [comment]
虽然已经有多个网友向我建议添加蓝奏云的支持，但是我觉得并无明显的必要性。

**Comment by TheBadZhang** [comment]
不啊，蓝奏云可以提供无需账号注册的高速下载服务，相比百度，天翼更加优秀，当然，有能力的人直接从github上下载肯定是一个更好的选择

**Comment by Guyutongxue** [comment]
同意添加蓝奏云链接。蓝奏云是专门为开发者提供的，允许用户高速下载他们想要的文件。我的部分项目也使用蓝奏云作为 GitHub Release 的备用链接。
