### ISSUE TITLE
帮人帮到底

### ISSUE THREAD

**Issue by HairlessVillager** [banzhusoft/devcpp-cn#15]
首先感谢作者就爱如 EGE 图形库。既然已经自带 EGE，请在编译选项里带上 EGE 的编译参数（“编译选项->编译器->在连接器命令行加入以下命令”）：

* 64位：`-static -libgcc -lgraphics64 -luuid -lmsimg32 -lgdi32 -limm32 -lole32 -loleaut32 -lwinmm -lgdiplus`
* 32位：`-static -libgcc -lgraphics -luuid -lmsimg32 -lgdi32 -limm32 -lole32 -loleaut32 -lwinmm -lgdiplus`

**Comment by banzhusoft** [comment]
我估计你没有阅读附带的使用了EGE、Direct3D和 OpenGL 的示例文件。
每一个文件里面都写清楚了需要使用相应的编译命令。
而且，不应该把某个专用库的编译命令添加到通用的编译参数中。

而且，我还准备添加对 EasyX 的支持。

**Comment by Guyutongxue** [comment]
> 我估计你没有阅读附带的使用了EGE、Direct3D和 OpenGL 的示例文件。
> 每一个文件里面都写清楚了需要使用相应的编译命令。
> 而且，不应该把某个专用库的编译命令添加到通用的编译参数中。
> 
> 而且，我还准备添加对 EasyX 的支持。

您好！我建议可以在 `编译选项 -> 代码生成/优化` 中提供 “链接 EGE 库" 的选项。

关于 EasyX 库，我想提示您：
1. EasyX 库是基于 MSVC 编译器开发的**闭源**动态链接库。所以您可能无法用在 MinGW 上；
2. 即便您成功获取了 MinGW 版本的 EasyX 库，您也无法将其直接与 Dev-C++ 打包：因为 Dev-C++ 的 GPLv2 协议**不允许**和闭源代码共同发行。您合法的做法只有提供下载链接，让用户自己操作。

**Comment by HairlessVillager** [comment]
> 我估计你没有阅读附带的使用了EGE、Direct3D和 OpenGL 的示例文件。
> 每一个文件里面都写清楚了需要使用相应的编译命令。
> 而且，不应该把某个专用库的编译命令添加到通用的编译参数中。
> 
> 而且，我还准备添加对 EasyX 的支持。

不好意思，我对编译参数的理解有误，给您造成困扰了，抱歉！

不过对于您说到“附带的使用了EGE、Direct3D和 OpenGL 的示例文件”，我**艰难**地在 Help 文件夹里面找到了“Dev-Cpp-EGE.htm”。不知能否将这个文件夹里面的内容变得更**显眼**一些（例如在初次安装时提示一下）？因为可能有新手拿着 EGE 的源代码准备编译却发现报错而不知如何是好。
