### ISSUE TITLE
请更新源代码

### ISSUE THREAD

**Issue by Guyutongxue** [banzhusoft/devcpp-cn#18]
您在 Release 中发布了版本 5.15，但我没有看到源代码的相关更新。

您正在开发**开源**软件，请您**先**提交并推送代码到 GitHub，**然后**再发布更新，以维护良好的开源生态。谢谢您的配合。

**Comment by banzhusoft** [comment]
我仅仅是忙于继续添加新的功能，没有及时更新源代码而已！


催促我及时更新源代码有什么意义呢？



我现在就把 5.15 发行版删除！






----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Guyutongxue "<notifications@github.com&gt;;
发送时间：2020年9月5日(星期六) 中午11:06
收件人："banzhusoft/devcpp-cn" <devcpp-cn@noreply.github.com&gt;;
抄送："Subscribed "<subscribed@noreply.github.com&gt;;
主题：[banzhusoft/devcpp-cn] 请更新源代码 (#18)
-----------------------------------

 

 
您在 Release 中发布了版本 5.15，但我没有看到源代码的相关更新。
 
您正在开发开源软件，请您先提交并推送代码到 GitHub，然后再发布更新，以维护良好的开源生态。谢谢您的配合。

**Comment by Guyutongxue** [comment]
请您遵守 GPL 协议赋予您的义务。当您使用该协议发行某一软件时，您应当保证任何人可以获取到当前这一版本的源代码。这是为了保证用户可以获得其所使用的软件的自由。

关于 GPL 为何做出这一强制约定，请您参阅自由软件组织在 Copyleft 这一方面的解释：http://www.gnu.org/licenses/licenses.html#WhatIsCopyleft

**Comment by banzhusoft** [comment]
好的，更新源代码是天大的事情，对吧！！！！

**Comment by banzhusoft** [comment]
我正忙于添加新功能，没有及时更新源代码，但是你现在反复地催我更新源代码，那是因为更新源代码是天大的事情，你急着要拿到我的源代码去添加很多新功能，对吧？

**Comment by Guyutongxue** [comment]
在开源领域，更新源代码就是比发行 Release 更重要的事情。您如果想在开源领域做出自己的贡献，就请遵守这一准则。

我并不是想要添加什么新功能。我只是提示您需要遵守开源协议，仅此而已。

最后，感谢您删除（已经潜在地违反了 GPL 的）v5.15 发行版。如果您想要发行下一版本，请在 GitHub 上更新源代码；或者在您的发行版中提供指向最新代码的链接。

**Comment by banzhusoft** [comment]
我非常反感您这样的开源警察！那么，我就把源代码删除吧！

**Comment by Guyutongxue** [comment]
我也非常反感您这种不遵守开源协议的开发者。而且，您在各个 Issue 下表现出的固执己见的态度也令人无法接受。您尽管删除此仓库，但与此同时您也要删除您相应的发行版本。我现在警告您，您若在不提供源代码的情形下发布发行版，则违反 GPL 赋予您的**法律**义务。

> 至于GPL在中国的知识产权法律体系下能否得到支持和保护就是另外的问题了，中国在知识产权保护方面就是呵呵。目前没有足够证据表明中国法律不承认GPL。违法就是违法，即使没人起诉也是违法。（知乎 @李子天）

您身为老师，应当为人师表，做正确的事情，为学生做榜样。您这样的行为可以认为是中国开发者和中国教师群体的耻辱。

**Comment by Guyutongxue** [comment]
https://zhuanlan.zhihu.com/p/101206609
请您自重。

**Comment by banzhusoft** [comment]
我就要这样玩。
