### ISSUE TITLE
病毒是怎么回事??????  virus is found !!!

### ISSUE THREAD

**Issue by lingbl** [banzhusoft/devcpp-cn#2]
![图片](https://user-images.githubusercontent.com/16526759/86875292-bd709480-c114-11ea-963f-a56e0b4e2d71.png)

**Comment by HairlessVillager** [comment]
Edge浏览器同样报毒

**Comment by banzhusoft** [comment]
原因可能是两个：
1、我使用了汉化版的 Inno Setup 进行打包，很多被汉化后的应用程序（可能对原发行文件进行了修改）都会被杀毒软件报告有病毒。2、在打包过程中没有做数字签名。

请相信这个软件的安全性。
如果信不过，请杀毒，并把报告为有病毒的文件删除。

**Comment by lingbl** [comment]
英文版可以不用汉化的 Inno Setup 打包

**Comment by banzhusoft** [comment]
现在发布了新版本 v5.14，请下载试用。

安装文件是使用英文版 Inno Setup 打包制作 的。希望它不会被报告带病毒了。
