### ISSUE TITLE
Notice that GPLv3 is not compatible with GPLv2!

### ISSUE THREAD

**Issue by Guyutongxue** [banzhusoft/devcpp-cn#3]
The original Dev-Cpp is licensed under GPLv2. But the current fork is licensed under GPLv3, which is not permitted by GPLv2. See https://www.gnu.org/licenses/gpl-faq.html#AllCompatibility for detail.

By the way, I can't find the source code now. I also have my own fork of [Dev-Cpp v5.12](https://github.com/Guyutongxue/orwelldevcpp), and I'd like to learn some new things from you. Thanks a lot.

**Comment by banzhusoft** [comment]
Thanks for your notice. I will replace the file "GPL.txt" with "GPLv2.txt" which contains GPL v2. And I will publish the release file today (without change the filename).

About the source code, I am just too busy to upload it. I am not familiar with Github Desktop now, but I will upload the source code as soon as possible.

**Comment by banzhusoft** [comment]
I repacked the release files and uploaded.

I uploaded all the source files to folder "Source" and uploaded all the release files to folder "Release".
(Installer file is generated by compiling "Dev-Cpp-5.14.iss" with Inno Setup.)

**Comment by Guyutongxue** [comment]
> I remade the installer file and uploaded.
> 
> And, I uploaded all the source files to folder "Source" and uploaded all the release files to folder "Release". (Installer file is generated by compiling "Dev-Cpp-5.14.iss" with Inno Setup.)

Thank you for all your hard work. :heart:
