### ISSUE TITLE
无法在 32 位 XP 系统上正常使用 TDM64-GCC 9.2.0 编译

### ISSUE THREAD

**Issue by skylee03** [banzhusoft/devcpp-cn#4]
您好，我最近也在维护一个叫做[My-Dev-C++](https://github.com/skylee03/My-Dev-Cpp)的Dev-C++发行版，不过可能不如您的版本完善。

我刚开始维护这个项目时，原版Dev-C++采用的TDM-GCC编译器已暂停维护多年，因此我转而采用MinGW-w64发布的发行版作为默认的编译环境。

由于前几个月TDM-GCC项目复活，因此我最近正在考虑重新采用它作为默认的编译环境。

但是当我在Windows XP 32位系统下测试时，发现无法正常编译，具体情况见我当时在TDM-GCC的Repo里开的一个[issue](https://github.com/jmeubank/tdm-gcc/issues/21)，不过并未收到解答。

以下是中文描述：

> 当我尝试在我的 64 位 Windows 10 计算机上使用 TDM64-GCC 9.2.0 编译一个仅包含单行代码`int main() {}`的 C++程序时，它工作得很好。但是在一个 32 位 Windows XP 系统上，它产生了如下错误信息：
> C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/32/libstdc++.a: file not recognized: file format not recognized collect2.exe: error: ld returned 1 exit status
> 然而，当我使用先前版本的 TDM64-GCC （例如，4.9.2 ）编译相同的程序时，它在 32 位 Windows XP 系统和 64 位 Windows 10 操作系统上都工作得很好。
> 我应当做什么来使得 TDM64-GCC 9.2.0 编译器在 32 位 Windows XP 系统上正确工作？

我发现您目前正在采用TDM64-GCC 9.2.0作为默认的编译器，因此我想要请教您，如何使TDM64-GCC正确在32位的Windows XP系统下工作？

**Comment by skylee03** [comment]
同样的问题在v2ex上发帖问过，不过并没有收到有效解答。

https://v2ex.com/t/690689

**Comment by banzhusoft** [comment]
很遗憾，我实际上并没有测试过包含TDM-GCC 9..0 的 Dev-C++ 是否能在XP上运行。
而且，我手头并没有运行XP系统的计算机，也没法测试。
所以没法回答你的问题。
如果你手头有运行XP系统的计算机，请测试并把结果告诉我。
如果确实是 TDM-GCC 9.2.0 本身的问题，那么我建议你改用 TDM-GCC 5.1.0。那是一个最接近原有的 4.9.2 的更新版本了。似乎在网上并没有介于 9.2.0 与 5.1.0 之间的其它版本。

**Comment by skylee03** [comment]
XP系统上的运行结果已在上面提及，即编译仅包含一行`int main() {}`的代码，输出如下错误信息：

> C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/32/libstdc++.a: file not recognized: file format not recognized collect2.exe: error: ld returned 1 exit status

**Comment by banzhusoft** [comment]
我的意思是说，请你把我打包制作的这个 Dev-Cpp-5.14.exe 安装在一台装有XP系统的计算机上进行测试。看是不是出现与你所说的一模一样的效果？

**Comment by skylee03** [comment]
> 我的意思是说，请你把我打包制作的这个 Dev-Cpp-5.14.exe 安装在一台装有XP系统的计算机上进行测试。看是不是出现与你所说的一模一样的效果？

安装包无法运行，提示“不是有效的 Win32 应用程序”。

**Comment by skylee03** [comment]
Inno Setup 6 起开始不支持Windows XP。
https://jrsoftware.org/files/is6-whatsnew.htm

**Comment by banzhusoft** [comment]
我检查过了，上面所说的编译问题 TDM-GCC 9.2.0 不再支持 Windows XP 系统所致，而且 Inno Setup 6 也不再支持 Windows XP 系统。因此，我改用 TMD-GCC 5.1.0 作为编译器、使用 Inno Setup 5.6.1 进行打包，制作了一个 **Dev-C++ 5.14 XP专用版**。下载链接见主页。

**Comment by skylee03** [comment]
感谢。TDM-GCC官网还说自己支持XP呢，白折腾一场。😓

**Comment by skylee03** [comment]
刚才在一个俄罗斯网站上似乎看到了一个解决方案：
https://www.linux.org.ru/forum/talks/15621121
不过我还没尝试过。

**Comment by banzhusoft** [comment]
我觉得，TDM-GCC 9.2.0 在xp上能否运行不是一个重要的问题。我也不想花太多时间在它上面。但是如果你确实想彻底解决这个问题，就应该向 tdm-gcc的作者去反映。我觉得应该让他来解决。

----------

该邮件从移动设备发送



--------------原始邮件--------------
发件人："Mingtian Yang "<notifications@github.com&gt;;
发送时间：2020年7月20日(星期一) 下午5:51
收件人："banzhusoft/devcpp-cn" <devcpp-cn@noreply.github.com&gt;;
抄送："BanzhuSoft "<anbangli@mail.ccnu.edu.cn&gt;;"Comment "<comment@noreply.github.com&gt;;
主题：Re: [banzhusoft/devcpp-cn] 无法在 32 位 XP 系统上正常使用 TDM64-GCC 9.2.0 编译 (#4)
-----------------------------------

 

 
感谢。TDM-GCC官网还说自己支持XP呢，白折腾一场。

**Comment by skylee03** [comment]
在原项目下开 [issue](https://github.com/jmeubank/tdm-gcc/issues/21) 反映过这一问题，不过作者并没有回应。[无奈]
