### ISSUE TITLE
Embarcadero也维护了一个fork

### ISSUE THREAD

**Issue by skylee03** [banzhusoft/devcpp-cn#5]
https://github.com/Embarcadero/Dev-Cpp

**Comment by HairlessVillager** [comment]
不是吧啊sir，这也有必要发一个issue？ヽ(`Д´)ﾉ

**Comment by skylee03** [comment]
> 不是吧啊sir，这也有必要发一个issue？ヽ(`Д´)ﾉ

毕竟是 Embarcadero，不是什么私人在维护。

**Comment by banzhusoft** [comment]
我几天前看到了那个项目，并且下载安装试用了。坦白地说，我认为那个项目做得比我的差得多。
但是因为作者顶着 Embarcadero 的名头，所以我也不好直接明说。
我在那个项目中开了一个话题，客气地请作者看一看我这个项目。
他回复说，我可以去帮助更新他的中文语言文件。哈哈~

我和他的这两个项目在 sf.net 上都建立了主页，
我的是：https://sourceforge.net/projects/devcpp20/
他的是：https://sourceforge.net/projects/embarcadero-devcpp/
他的项目建立于 7月12日，但是本周下载数量比我的要多。
