### ISSUE TITLE
可以换一个新图标

### ISSUE THREAD

**Issue by Guyutongxue** [banzhusoft/devcpp-cn#6]
比如这样的：
![newicon](https://s1.ax1x.com/2020/07/27/aihePO.png)

主要原因就是：
- 原来的图标看上去就很“老”，没有活力
- 新图标可以和老版本形成显著区分

我在本地测试过，显示效果还可以。

**Comment by banzhusoft** [comment]
谢谢你热心制作的图标。
但是软件图标虽小，要做得美观大方却不是一件简单的事情。
新版本的工具栏和菜单中有我自己制作的 4 个小图标（切换注释、新建...、上一个书签和下一个书签），花了不少时间，但是自己并不很满意。
至于软件的主图标，恐怕需要将来能有专业的图标制作者参与为好。

**Comment by Guyutongxue** [comment]
我赞成您的观点。我也注意到您在软件内嵌入的新图标，但说实话和其它图标的整体风格并不是特别相符。更改图标这件事情确实有很大难度，或许让一些专业设计师来重新设计它们是最好的办法。
