### ISSUE TITLE
中文页面乱码

### ISSUE THREAD

**Issue by TomSawyer404** [banzhusoft/devcpp-cn#7]
我的Windows10开启了UTF-8编码。我发现此版本的dev-cpp在UTF-8编码下和原版一样是乱码的。希望有人能完善软件。
dev-cpp轻便的调试功能是我所欣赏的，这样我就不用每次调试都得跑到VS2019去了。
![1](https://user-images.githubusercontent.com/47690109/88612861-b9ee7e80-d0be-11ea-993b-387cc1fefbf0.png)

**Comment by banzhusoft** [comment]
请截图告诉我 “我的Windows10开启了UTF-8编码” 是怎么设置的？然后我再考虑如何解决此问题。

**Comment by banzhusoft** [comment]
哈，我想出来乱码原因和解决办法了。
原因是，界面语言文件（Lang目录下的 Chinese.lng、Chinese.msg和Chinese.tips）是按照ANSI编码保存的，在UTF8编码下就会出现乱码。
解决办法是，用一个文本编辑器（例如notepad2）分别打开这几个文件并重新改成UTF8编码，保存。
