### ISSUE TITLE
代码折叠功能的异常

### ISSUE THREAD

**Issue by HairlessVillager** [banzhusoft/devcpp-cn#9]
如下图所示，左键单击减号时无反应或仅是将该行设置断点。

![](https://s1.ax1x.com/2020/08/05/arA0Gq.png)

**Comment by HairlessVillager** [comment]
图片链接：https://imgchr.com/i/arA0Gq

**Comment by banzhusoft** [comment]
这是故意设计成这个样子，以防初学者点击时出现代码折叠之后感到惊奇而不知所措。
熟练使用者如果要使用代码折叠，需要在“编辑器选项” 的 “基本” 选项卡中勾选 “点击以折叠或展开代码”。

**Comment by HairlessVillager** [comment]
如果是这样的话，那么能否在代码折叠功能未开启的情况下自动将“装订线上显示代码折叠”功能关闭呢？或者能否将这两个选项合并成一个选项？

**Comment by banzhusoft** [comment]
根据实际教学经验，应该让初学者可以方便地看出复合语句之间的关系，但是又不让他们随意点击而折叠/展开。
所以就设计成这样，不想更改。

**Comment by HairlessVillager** [comment]
行吧

**Comment by Guyutongxue** [comment]
“行号边上的减号”是一个约定俗成的标志，表示这里可以收起/展开。一个软件的设计应当符合通用的设计语言；如果这里画着“可以收起”的标志却不能收起，会有更多的用户感到奇怪，提出问题甚至质疑软件质量。（因为并不是所有用户都会去设置里寻找答案。）编写一个软件既要考虑到对初学者的友好，又要考虑对那些“老手”的使用体验。

我的建议是：在保证显示复合语句层级的前提下，隐藏减号但不隐藏其它线段，只有开启折叠功能后才显示减号。

**Comment by zxp2019** [comment]
我希望这个软件不只是为了初学者而设计的。

**Comment by zxp2019** [comment]
我学 C++ 语言第一天就掌握了这个功能，而且并没有觉得“惊奇而不知所措”。

**Comment by HairlessVillager** [comment]
> 我希望这个软件不只是为了初学者而设计的。

附议，但是目前看来这个 IDE 是优先考虑新人的使用体验。作者也有难处，都互相体谅一下吧~

**Comment by zxp2019** [comment]
> 
> 
> > 我希望这个软件不只是为了初学者而设计的。
> 
> 附议，但是目前看来这个 IDE 是优先考虑新人的使用体验。作者也有难处，都互相体谅一下吧~

好的
